Adding skip-deploy bitops configuration option
bitops-plugins/terraform pull request #13
Opened 2022-11-03 19:49 UTC by PhillypHenning

2022-11-04 13:51 UTC, LeoDiazL commented
Code looks good.

2022-11-07 20:11 UTC, armab requested changes
Looks like we're missing some documentation updates here and there:

https://github.com/bitops-plugins/terraform#terraform-bitops-schema
https://github.com/bitops-plugins/terraform#skip_deploy_terraform
https://bitops.sh/tool-configuration/configuration-terraform/

Please also update the PR title to be more clear what this PR is all about.

2022-11-07 20:11 UTC, armab commented on bitops.schema.yaml
> +            export_env: TERRAFORM_SKIP_DEPLOY
Can we document it in the README as well?

Same is required for the official docs https://bitops.sh/tool-configuration/configuration-terraform/

2022-11-07 20:11 UTC, armab commented on deploy.sh
> +if [ "$SKIP_DEPLOY_TERRAFORM" == "true" ] || [ "$TERRAFORM_SKIP_DEPLOY" == "true" ]; then
What's the difference between `SKIP_DEPLOY_TERRAFORM` and `TERRAFORM_SKIP_DEPLOY`?

2022-11-07 20:22 UTC, armab commented on deploy.sh
>    echo "SKIP_DEPLOY_TERRAFORM is set.  Skipping."
If we're replacing old format ENV `TERRAFORM_SKIP_DEPLOY` with a new one `TERRAFORM_SKIP_DEPLOY ` then message should be updated to a new version too: 
```suggestion
  echo "TERRAFORM_SKIP_DEPLOY is set.  Skipping."
```

2022-11-10 13:57 UTC, PhillypHenning commented
- configuration schema added to schema (https://github.com/bitops-plugins/terraform/tree/skip-patch#skip-deploy)
- Removed references to `SKIP_DEPLOY_TERRAFORM` environment variable
- https://github.com/bitovi/bitops/pull/354

2022-11-10 13:59 UTC, armab approved these changes
👍

2022-11-10 14:00 UTC, merged